### ISSUE TITLE
grunt-contrib-less breaks on less generated by grunt-spritesmith

### ISSUE THREAD

**Issue by vehdad** [twolfson/grunt-spritesmith#171] opened 2019-05-22 11:31 UTC
Sorry for opening issue but I am stuck with old app running number of grunt tasks, among others grunt-contrib-less for less files and grunt-spritesmith for building sprites.

After updating to the less 3.0.0 I updated to the grunt-contrib-less: 2.0.0 and spritesmith accordingly to the 6+ version.

I generate sprites and I get respective files (sprite image and corresponding less file). One of next steps is to combine all less files in one style.css file. 

When I run less task it breaks on sprites.less on line:
@spritesheet: 576px 576px '../../img/icons.png' @spritesheet-sprites;
with an error
[L472:C0] Cannot read property 'eval' of null

Running "less:dev" (less) task

src\assets\style\cando-ui\sprites.less: [L472:C0] Cannot read property 'eval' of null
Warning: Error compiling src/assets/style/style.less Use --force to continue.

All dependencies are met.

-- grunt@1.0.4
-- grunt-contrib-less@2.0.0
-- grunt-spritesmith@6.6.3
-- grunt-cli@1.3.2

I also tried compiling less file through online compiler and it works until the very same line.

**Comment by twolfson** [comment] 2019-05-22 14:51
Just getting back from a long vacation. I'll take a look at this within the
next 2 weeks

**Comment by vehdad** [comment] 2019-05-23 11:08
I hope you had nice vacation.. :) 
I am also trying to go deeper and see if there may be some other cause. If I find anything, I will post.
Thanks

**Comment by twolfson** [comment] 2019-05-26 21:18
Looking into this now. So far I have partially reproduced though I'm seeing a different error message:

```
AssertionError [ERR_ASSERTION]: { [Error: Inline JavaScript is not enabled. Is it set in your options?]
  message: 'Inline JavaScript is not enabled. Is it set  === null
```

This was after upgrading from `less@~1.5.1` to `less@~3.9.0`

**Comment by twolfson** [comment] 2019-05-26 21:25
Okay, that inline JS error is being caused by:

```
  @sprite-image-bare: ~`"@{sprite-image}".slice(1, -1)`;
```

which I believe is unavoidable due to double quoting in the past but I'm happy to revisit that. Still trying to reproduce your error though...

**Comment by twolfson** [comment] 2019-05-26 21:36
I believe the error you were seeing is the same as I was receiving. It looks like LESS introduced functions we can use to avoid the JS-based string escaping (e.g. `e`). Its purpose was to generate strings like:

```
  background-image: url(nested/dir/spritesheet.png);
```

as opposed to with quotes as LESS wanted:

```
  background-image: url('nested/dir/spritesheet.png');
```

Right now I'm looking into when these were introduced to determine compatibility issues

**Comment by twolfson** [comment] 2019-05-26 21:45
It looks like `e` existed as far back as 1.5.1 but we never discovered it. Updated everything to use it and pushing minor releases

**Comment by twolfson** [comment] 2019-05-26 21:50
This has been patched and released in:

- `spritesheet-templates@10.3.0`
- `grunt-spritesmith@6.7.0`
- `gulp.spritesmith@6.10.0`

Thanks for the bug report!

**Closed by twolfson** 2019-05-26 21:50 UTC
